channels:
- conda-forge
- defaults

dependencies:
  - python=3.8
  - cartopy
  - cmocean
  - cfgrib
  - eccodes
  - xarray
  - jupyter
  - pip
  - pip:
    - planetary_computer==0.4.9
    - odc-stac==0.2.4
    - datacube==1.8.5
    - pystac==1.5.0
    - geopy==2.2.0
    - shapely==1.8.0
    - rasterio==1.2.10
    - sqlalchemy==1.4.46
    - pqdm
    - pandas
    - numpy
    - scikit-learn
    - lightgbm
    - matplotlib
    - gdown
    - git+https://github.com/blaylockbk/Herbie.git
